---
apiVersion: mirror.plugin.fluxcd.io/v1beta1
kind: Config
charts:
  - name: frr-k8s
    source: https://metallb.github.io/frr-k8s
    destination: oci://ghcr.io/soulwhisper/charts
    # renovate: datasource=helm depName=frr-k8s registryUrl=https://metallb.github.io/frr-k8s
    version: "0.0.26"
    limit: 3
