---
apiVersion: mirror.plugin.fluxcd.io/v1beta1
kind: Config
charts:
  - name: ceph-csi-drivers
    source: https://ceph.github.io/ceph-csi-operator
    destination: oci://ghcr.io/soulwhisper/charts
    # renovate: datasource=helm depName=ceph-csi-drivers registryUrl=https://ceph.github.io/ceph-csi-operator
    version: "1.0.4"
    limit: 3
