---
apiVersion: mirror.plugin.fluxcd.io/v1beta1
kind: Config
charts:
  - name: ceph-csi-drivers
    source: https://ceph.github.io/ceph-csi-operator
    destination: oci://ghcr.io/soulwhisper/charts
    version: "*"
    limit: 3
