[settings]
disable_hints = ["*"]
experimental = true
idiomatic_version_file_enable_tools = ["node", "python", "go", "rust"]

[tools]
claude-code = "latest"
gh = "latest"
just = "latest"
jq = "latest"
prek = "latest"
tmux = "latest"
uv = "latest"
yq = "latest"
