---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Validate Pull Request

on:
  merge_group:
  pull_request:

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.changed_files }}
    steps:
      - name: Get changed files
        uses: bjw-s-labs/action-changed-files@v0.6.0
        id: changed-files
        with:
          path: apps
          include_only_directories: true
          max_depth: 1

  build:
    if: ${{ needs.prepare.outputs.changed-files != '' && needs.prepare.outputs.changed-files != '[]' }}
    name: Build and test
    needs:
      - prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJSON(needs.prepare.outputs.changed-files) }}
      fail-fast: false
      max-parallel: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        if: ${{ matrix.app != '__skip__' }}
        uses: docker/setup-buildx-action@v4

      - name: Add include directory to build context
        run: |-
          rsync -a --ignore-existing --progress ./include/ ./apps/${{ matrix.app }}/

      - name: Build image
        uses: docker/bake-action@v7
        id: bake
        with:
          load: true
          push: false
          files: ./docker-bake.hcl
          source: ./apps/${{ matrix.app }}
          targets: image-local
        env:
          GIT_SHA: ${{ github.sha }}

      - name: Set up Go
        if: ${{ matrix.app != '__skip__' }}
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Run Tests
        shell: bash
        env:
          APP: ${{ matrix.app }}
          TESTCONTAINERS_RYUK_DISABLED: "true"
          TEST_IMAGE: ${{ fromJSON(steps.bake.outputs.metadata)['image-local']['image.name'] }}
        run: |-
          echo "Running tests against ${TEST_IMAGE}"
          go test -v ./apps/${APP}/...

  build-success:
    needs:
      - build
    if: ${{ !cancelled() }}
    name: Build and test - Success
    runs-on: ubuntu-latest
    steps:
      - name: Any jobs failed?
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: All jobs passed or skipped?
        if: ${{ !contains(needs.*.result, 'failure') }}
        run: echo "All jobs passed or skipped"

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
